version: '2.1'

volumes:
  news-scraper-workers-daily-go:
  news-scraper-workers-historic-go:


services:
  news-scraper-workers-historic-go:
    build: .
    restart: always
    network_mode: "host"
    env_file:
      - .env_historic
  news-scraper-workers-daily-go:
    build: .
    restart: always
    network_mode: "host"
    env_file:
      - .env_daily